# Generated by Django 2.0.2 on 2018-02-27 10:58

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]
