# Generated by Django 2.0.2 on 2018-03-24 22:57

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='Your Answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='documents',
            field=models.ManyToManyField(blank=True, help_text='Press and hold Ctrl or Cmd to select multiple options and unselect options.', to='qanda.Document', verbose_name='Related Documents'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=markdownx.models.MarkdownxField(verbose_name='Document Content'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
    ]
